name: Unity_CSharp_Checkstyle

on:
  push:
    branches:
      - main

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: actions/setup-unity@v1
        with:
          unityVersion: '2020.3.26f1'
          components: 'unity,webgl,android'
          license: '${{ secrets.UNITY_LICENSE }}'

      - name: Install Code Analysis tools
        run: dotnet tool install -g microsoft.codeanalysis.analyzers

      - name: Check style project
        run: |
          unity-editor -batchmode -projectPath ./path_to_your_project -executeMethod BuildScript.RunCodeAnalysis -quit
