name: WPF_Style_Check

on:
  push:
    branches:
      - main  # Здесь укажите вашу основную ветку

jobs:
  check_style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Укажите актуальную версию .NET SDK

      - name: Install StyleCopAnalyzers
        run: dotnet add package StyleCop.Analyzers --version 1.3.2  # Укажите актуальную версию пакета StyleCop.Analyzers

      - name: Check code style
        run: dotnet build /p:StyleCopEnabled=true /p:StyleCopConfig=.stylecop.json  # Укажите имя вашего файла с настройками StyleCop
