name: Unity_CSharp_Checkstyle

on:
  push:
    branches:
      - main

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check style project
        run: |
          unity-editor -batchmode -projectPath ./path_to_your_project -executeMethod BuildScript.RunCodeAnalysis -quit
