name: Unity_CSharp_StyleCheck

on:
  push:
    branches:
      - main

jobs:
  style_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.0'

      - name: Install StyleCop.Unity
        run: |
          dotnet tool install -g StyleCop.Unity.Analyzers

      - name: Check code style
        run: |
          dotnet stylecop.unity -p . 
