name: CSharp_Style_Check

on:
  push:
    branches:
      - main

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.0' 

      - name: Install StyleCop analyzers
        run: dotnet tool install -g StyleCop.Analyzers

      - name: Run StyleCop analysis
        run: dotnet build /p:WarningLevel=0 # Это запускает анализаторы стиля в проекте
